### ISSUE TITLE
Invoke-webrequest fails if you disable TLS 1.0

### ISSUE THREAD

**Issue by alainassaf** [sacha81/StoreFront-HealthCheck#8]
Hello,

We recently had a company-wide action to disable TLS 1.0 where ever we could. After this, the StoreFront-HealthCheck script failed to show that our Store URL was reachable. I did some checking and found this on Technet - https://social.technet.microsoft.com/Forums/en-US/00b78ac4-cadb-4566-b175-beb9d34a9093/how-to-use-tls-11-or-12-for-invokewebrequest.

Apparently, invoke-webrequest defaults to TLS 1.0, so setting the security protocol to something other than TLS 1.0, allows the command to work. In your script, I added the following line: 
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

before `$httpstatus = (Invoke-WebRequest -Uri $DeploymentHostbaseUrl)`

Now our report is correct.

Thanks,
Alain

**Comment by sacha81** [comment]
thanks Alain, I added this to the code.
